spring:
  application:
    name: Review Moderation System

  threads:
    virtual:
      enabled: true

server:
  port: 8080

prediction:
  pipeline:
    url: ${PREDICTION_PIPELINE_URL:http://localhost:8000/predict}
