version: '3.8'

services:
  review-moderation-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: review-moderation-system:latest
    container_name: review-moderation-app
    ports:
      - "8080:8080"
    environment:
      - PYTHON_SCRIPT_PATH=run_model.py
      - PYTHON_WORKING_DIR=/app
      - PYTHON_VENV_PATH=python3
      - PYTHON_VENV_ACTIVATE=false
      - JAVA_OPTS=-Xmx512m -XX:+UseG1GC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M
